<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Form Matching Rule</name>
  <uuid>24c23d26-a4a3-4d7a-b872-4ca5a99b47e5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Form Data Sent' is 'Form Data Received'
then
	set decision to "Full Match" ;
Else set decision to "Mismatch";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
