<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Recipient Matching Rule</name>
  <uuid>2a490373-9ca5-4880-834f-0564c7da662f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Authorised Recipient of 'Form Sent' is the Authorised Recipient of 'Form Received'
then set decision to "Full Match" ;
else set decision to "Mis Match";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
