<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Mailing Address Matching Business Rule</name>
  <uuid>7bcaac9c-8255-43ba-ab57-ae1da4fdc2e7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Mailing Address of 'Form Sent' is the Mailing Address of 'Form Received'
then
	set decision to "Full Match" ;
else set decision to "Mis Match" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
