<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Titile Matching Rule</name>
  <uuid>69c2f9e5-1d8c-4e9e-8c33-dac0b34170f1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Titile of 'Form Sent' is the Titile of 'Form Received'
then
	set decision to "Full Match" ;
else set decision to "Mis Match" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
